- .github/workflows/build_pipeline.yml
- .gitignore
- requirements.txt
- scripts/.coveragerc
- scripts/code-coverage.sh
No actual parse challenge changes included here, just the build pipeline stuff, but I think it would be good to get that into master ASAP.
Now with added Slack notifications for build pipeline results, a feature we don't yet have on any other project:
> Mf parse challenge

- pam/activity.py
- pam/core.py
- pam/parse.py
- tests/test_2_activity_plan.py
Ready for merge please:
Some minor bits and bobs while i was trying to get around some grubby edge cases. Main addition of note is that fill_plan() will default to stay_at_home() if it cannot find a home location about which to 'pivot' or fill the plan. I've therefore also improved the gathering of home location from parse.read_travel_diary
> hack some fixes for parsing real sample

- .github/workflows/build_pipeline.yml
- scripts/.coveragerc
Waffeur thin PR to fix the build and change the Slack channel to which we send build notifications.
> Michael change slack channel for build messages

- pam/extract_OD_matrices.py
This is a function to extract OD matrices from Population and save it in a csv file. Please let me know how you think! :)
> Od matrices

- scripts/.coveragerc
Dirty. Feel dirty. Took 7 showers, but couldn't shake the feeling. Dirty.
> Lower code coverage threshold to fix build. Shameful.

- pam/write.py
This is a function to create csv files containing populations, households, people, activities and legs. 
These files can then be used as an input to a dashboard tool (in this case Power BI) to create statistics. Attached is a dashboard POC to show what kinds of things can be done with these csv files. 
[Dashboard POC.pptx](https://github.com/arup-group/pam/files/4558443/Dashboard.POC.pptx)
NOTE: The build is failing at the moment because I didn't include any tests with my code and therefore code coverage is slightly below the threshold. I'm working with mfitz to resolve this. Please do send your review comments in the meantime.
> adds a function to export all population data to csv files 

- pam/core.py
- pam/read.py
- tests/fixtures.py
- tests/test_3_parse.py
- tests/test_3_parse_activity_plan.py
- tests/test_3_parse_challenge.py
- tests/test_3_parse_matsim.py
- tests/test_8_write.py
Gotta mergem all - just a few pickle methods with tests.
> rename parse as read module and adds pickle methods

- .gitignore
- pam/core.py
- requirements.txt
- scripts/.coveragerc
- scripts/data-synthesis/trip_synthesiser.py
- scripts/performance/activity_loader.py
- scripts/performance/perf-report.css
- scripts/performance/perf-report.html.jinja
- scripts/performance/population-builder-profile.sh
- scripts/performance/report_builder.py
Adds the tools to profile PAM's population building functionality and generate an HTML report.
See https://docs.google.com/presentation/d/1KjirBAyCfO1aZkAjkF2_f1TFWmq7DhkQ5Xw-BA5zQfI/edit#slide=id.g84d8f8a363_1_0
> Michael measure parse performance

- pam/plot/stats.py
- tests/test_10_plotting.py
Added some code to plot high level comparisons between scenarios. Please see the attached picture for example outputs. 
I've created a lot of helper functions so that it is still possible to plot each graph individually instead of all four at the same time. 
Added one test that checks that graphs are plotted and does a spot check on some of the stats. 
Any comments welcome!
> added code to plot scenario comparisons

- pam/write.py
Added the frequency field to the csv export
> added frequency to export files

- notebooks/NTS Population Synthesis Example.ipynb
- pam/samplers/facility.py
- requirements.txt
- tests/test_9_samplers.py
updates NTS pop synth example notebook. Minor changes to facility sampler and dependabot req update.
> Uk scenario

- pam/activity.py
- pam/core.py
- pam/write.py
- tests/test_1_core.py
- tests/test_1_core_operations.py
place holder PR, tests still to be added
> adds operations

- .gitignore
- pam/activity.py
- pam/write.py
- tests/test_8_write.py
See tickets LAB-823 and LAB-815 for description. Adds a method for extracting benchmark data from a PAM population, for specified combinations of data fields, dimensions, and aggregation functions.
> Benchmarking

- pam/activity.py
- pam/core.py
- pam/read.py
These read methods need proper organisation and docs. But this adds the ability to leave the hh zone in the hh table input...
> input hack for hh zone

- pam/samplers/facility.py
Responds to this request: https://github.com/arup-group/pam/issues/67
Enables exporting/loading the spatially joined facilities-zones geodataframe ("activity_areas") from/to the FacilitySampler. By using this method, we can then save time across sampling iteration of the same data, by avoiding the expensive joining part.
To use it, build the facility sampler as usual, and the export the activity areas with `facility_sampler.export_activity_areas(filepath = "activity_areas.pkl")`. Then, next time we initiate/build the facility sampler we can pass the `activity_areas_path` argument to directly read the activity areas into the object (ie `facility_sampler = `FacilitySampler(....., activity_areas_path="activity_areas.pkl").
@akay-arup  Please let me know how much of a time improvement this PR …
> enable exporting / loading of joined facility-zone geodataframe

- notebooks/notebook_smoke_tests.py
Extremely trivial and picky, but the extra whitespace was bothering me. Also did some refactoring to make `main` cleaner.
**Before**
**After**
> Remove unnecessary whitespace from notebook smoketest summary

- pam/samplers/spatial.py
- tests/test_9_samplers.py
Iseul I add you to this PR for old times sake :)
This deals with the "archepelago" problem - where the existing random point sampler was failing to sample valid points on very sparsely distributed islands.
Modifies the random point sampler to deal with most shapes that can be thrown at it, including points, lines and the multi-varieties. This should now handle islands much better - provided they are multipolygons. Additionally will default to a random point within the shape bounds.
Tested pretty well. Passes coverage and notebook smoke tests.
> fixes multiploygon random point sample

- pam/write.py
- tests/test_8_write.py
The write_travel_diary method is basically a copy of the to_csv method.
This commit removes the redundant code. I have compared test_8_write.dy results and they look exactly the same.
> Consolidate write_travel_diary

- pam/samplers/facility.py
Small refactoring with large impact on the facility sampler build speed. Testing with a fairly large facilities/zones dataset, it shaved off more than 90% of the `FacilitySampler.build_facilities_sampler` method runtime.
The spatial join between zones and activities is still slow, but I don't think it can be improved further. However, the already implemented `export_activity_areas` and `load_activity_areas` methods allow to skip that step in subsequent iterations. Another option could also to make the spatial join part of OSMOX (as in most cases it only needs to happen once per project).
> facility sampler speed improvements

- .gitignore
- pam/samplers/attributes.py
- pam/samplers/basic.py
- pam/samplers/facility.py
- pam/samplers/spatial.py
- tests/test_9_samplers.py
Passed seed parameter in `attributes.py`, `basic.py`, `facility.py`, and `spatial.py` samplers to ensure that sampling facility locations is reproducible. Default seed is `None` which does not fix the pseudonumber generator's seed.
> Reproducible sampling

- pam/write.py
very simple convenience method for writing batches of the "pam benchmarks".
> adds write batch of bms

- pam/samplers/facility.py
just a little debug that was required to run the fac sampler. Not sure why
> fix complex sampler

- pam/samplers/population.py
- pam/utils.py
- tests/test_11_population_sample.py
adds population (freq) sampler function for convenience (I use it a lot)
> adds population sampler

- pam/core.py
- tests/test_1_core_operations.py
adds Person methods that make "last components" available for convenience, eg:
```
person.last_component  # can be either Leg or Activity or None for empty plan
person.last_activity  # can be an Activity or None
person.last_leg  # ...
```
> adds get last components interface

- pam/read.py
small PR to enable reading observed leg distance data from travel diaries.
> read travel distance from diaries

- pam/read.py
- pam/write.py
- tests/test_3_read_matsim.py
- tests/test_8_write.py
- tests/test_utils.py
moves matsim read write functions to default to "version 12"
> V12 io default

- pam/activity.py
- tests/test_2_activity_plan.py
simple convenience iterator for activity.Plan class. yields lists of legs within a trip.
> adds trip leg iter

- pam/samplers/tour.py
- tests/test_09_samplers_tour.py
Update functionality to normalise density and plot the spatial difference in inputs vs. outputs.
> update normalisation & tests

- pam/cli.py
Adds feature. Fixes #160 
Before: 
After:
Expected result: pam, version 0.0.1
Actual result:
> feat cli fixes #160 adds "pam --version"

- pam/planner/od.py
fixes a bug when creating OD matrices from the factory.
> fix ODFactrory bug

- docs/get_involved.md
- docs/installation.md
Fixes #203 by adding additional information to the installation and dev instructions.
> Update install and dev instructions in docs

- CHANGELOG.md
- docs/installation.md
- docs/static/hooks.py
- mkdocs.yml
- mkdocs_plugins/api_generator.py
- mkdocs_plugins/test_api_generator.py
- setup.py
I've not bothered to add a changelog for v0.2.0 as it is effectively the first official release of PAM - there were too many changes prior to this to collate retroactively.
> Add changelog

- CHANGELOG.md
- README.md
> fix badge urls

- examples/01_basics.ipynb
> togther -> together

- examples/02a_tabular_read_write.ipynb
added comment to workbook as per joss feedback [here](https://github.com/openjournals/joss-reviews/issues/6097#issuecomment-2031440883).
> adds note on load time

- CITATION.cff
- README.md
adds joss citation as per [link](https://github.com/openjournals/joss-reviews/issues/6097#issuecomment-2072154284)
> adds JOSS citation

- .cruft.json
- requirements/dev.txt
Fixes #280 
Best not to ignore a failing cruft check CI job on PRs (was failing in the last two PRs)! Just requires running `cruft update` locally with the `pam` conda env activated.
> Update to latest template version
