pam/parse.py

Added an option of randomly sampling the travel population when loading travel diaries. 
For example, parse.load_travel_diary(trips, attributes, sample_perc = 0.01) will only load 1% of the travelers, with trip frequency used as the probability weight.

Travel Diary sampling

---

notebooks/london-workers-classification.ipynb
pam/samplers/attributes.py
scripts/.coveragerc
tests/test_9_samplers.py

Adds a prelim [notebook](https://github.com/arup-group/pam/blob/london-worker-classification/notebooks/london-workers-classification.ipynb) for person classification as 'able to wfh' and 'key worker' - based on NOMIS employment stats for London. The methodology is pretty janky:
1. using SOC2010 level 2 employment categories (this is currently a big dictionary in the notebook):
1.1 manually map to lopops occupation categories
1.2 manually classify as  'able to wfh' and 'key worker'
2. based on london population for each category (gender, occ and work status (ft/pt):
2.1 wrangle tables so that frequencies are exposed for  'able to wfh' and 'key worker'
2.2 convert to probability based on frequency
2.3 build distribution dicts
eg:
`{'occ1': {'ft': {'male': 0.5, 'female': 0.4}...`
Note that …

London worker classification

---

.github/workflows/build_pipeline.yml

A fix for the CD build introduced for https://arupdigital.atlassian.net/browse/LAB-1098.
Caused this error in the [CodeBuild job](https://eu-west-1.console.aws.amazon.com/codesuite/codebuild/758645626094/projects/pam/build/pam%3A9968e11b-0282-4b30-9894-84806ee2786c/?region=eu-west-1), because there was no file called `release` inside the zip file (the CodeBuild job spec sets the env var via `SHA=$(cat release)`, hence `$SHA` is empty when read):
```
...
Step 6/6 : ENTRYPOINT python3
--
495 | ---> Running in dd01aa257ef2
496 | ---> ecc1247f3955
497 | Removing intermediate container dd01aa257ef2
498 | Successfully built ecc1247f3955
499 | Successfully tagged pam:latest
500 |  
501 | [Container] 2021/03/19 12:50:40 Running command docker tag $IMAGE_REPO_NAME $REPOSITORY_URI:$SHA
502 | Error …
```

Fix release file creation in CI build

---

pam/write.py
tests/test_8_write.py

Very small fix to pam.write.
Seems like recent changes require writing the household location attribute as `hzone` rather than `zone` -- or else read will fail to pick it up, with this error:
https://github.com/arup-group/pam/blob/663f49d36b1c8533d44a6d71582b697eeee91d7f/pam/read.py#L236

zone -> hzone in write

---

requirements.txt
tests/test_utils.py

There has been a change in Pandas version `1.3.0` around the test utility function `assert_frame_equal` (see the [release notes](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.3.0.html#other)). Although I didn't look into exactly why this bug fix breaks some of our tests, regressing to Pandas `1.2.5`, which is the latest version that is older than `1.3`, fixes our tests.
I was able to reproduce the test failures locally via `pip install pandas==1.3.0`, and then fix via `pip install pandas==1.2.5`.
It may be worth someone with knowledge of the code and tests having a quick look to make sure the tests in question are not relying on broken behaviour in `assert_frame_equal()`.
The [build now completes](https://github.com/arup-group/pam/runs/3104892398?check_suite_focus=true).

Pin pandas version to fix unit tests

---

.github/workflows/build_pipeline.yml

Zip files are still being pushed to S3 by the CI build, as evidenced by the first zip file below, timestamped from a few minutes ago:
```bash
2021-09-06 10:04:18   29675625 ZXNljHl.zip
2021-08-26 15:05:11   24273416 thOjyJ2.zip
...
```

Make S3 code bucket a build variable

---

requirements.txt

Change from Rtree==0.9.4 to 0.9.7. `pip install -e` fails with Rtree==0.9.4.

Updated Rtree version

---

pam/utils.py
tests/test_utils.py

Minor change to enable reading MATSim output plans in PAM. As some person activities or legs may continue to the next day, the MATSim plan reader needs to be able to read timestamps such as ("25:00:00").

read matsim second day acts

---

.gitignore
pam/activity.py
pam/core.py
pam/location.py
pam/read.py
tests/test_2_activity_plan.py
tests/test_3_read_travel_diary.py

Tries to bring more consistency when assigning home locations to persons. If a household location exists, it will get assigned as the `home_location` for every household member. This ensures that all household members will have the same home location, and that agents without any activities ("stay at home") will still have a location.
If there is no household location, PAM will infer the home location from the trips/activities table.

Home area fix

---

.github/workflows/daily-scheduled-ci.yml

A minimal daily scheduled CI build that runs the unit tests in an attempt to uncover any problems caused by having loosened our version constraints on some of our dependencies.
See https://arupdigital.atlassian.net/browse/LAB-1639.
Note that, for security reasons, new Actions workflows do not run until they have been created in the default branch, so we won't see this scheduled build start to run until after this PR has been merged.

Add a daily scheduled CI build

---

pam/array/decode.py
pam/array/distance.py
pam/array/encode.py
pam/utils.py
pam/variables.py
tests/test_14_encode_array.py

no one really needs this PR yet but i think it's kind of cool:
mostly implements a function to transform a Plan into a one-hot encoded array:
```
from pam import array
encoded = array.encode.plan_to_one_hot(
plan=plan,
mapping={"home":0, "work":1, "travel":2},
bin_size=3600,  # seconds
duration=86400  # seconds
)
```
This proves a 2d numpy array with the first dimension representing time bins and the second a one-hot encoding of activity and travel, eg:
```
[[1,0,0],[1,0,0],[0,1,0],[0,0,1]...]  # home-home-travel-work...
```
This is designed to work with the VAE experiments (although this returns only the array for a single plan and is only 2d, whereas existing experiment have a third dimension (which is redundant)).
also provides a "decode" function, such that plans can be (mostly) …

implements one-hot encode decode and distances

---

README.md
pam/cli.py
tests/test_16_cli.py

Allows down- or up-sampling a MATSim (xml) population via the command line, by invoking: `pam sample <path_population_xml> <path_core_area_geojson> <path_output_directory> -s <sample_percentage> -v <matsim_version>` 
For example, we can decrease the size of a hypothetical `plans.xml` file from 1000 agents to 100 by running `pam sample plans.xml output/resampled -s 0.1`.

sample cli

---

requirements.txt
scripts/code-qa/notebook_smoke_tests.py

You can now optionally pass one or more notebook paths as params to the python script, where before you could pass only a directory from which the list of notebooks would be discovered.
This was mostly just to give me a faster feedback loop than running all the notebooks while working on these changes, but could still be generally useful in situations where you're making changes to one or two notebooks and want the same sort of fast feedback. For example:
```bash
python scripts/code-qa/notebook_smoke_tests.py \
-k pam \
-k python37364bit373pyenve4f55e1c90f74740a9da8a10ea80341d \
-k python3 \
-n 'examples/03_PAM-Create-Population.ipynb' \
-n 'examples/12_Travel plots.ipynb' \
-n 'examples/10_PAM-stats.ipynb' \
-n 'examples/16_vehicles.ipynb MAKE THIS FAIL'
```

Nice up the notebooks smoke test report

---

examples/09_pam-geo-sampling.ipynb
pam/__init__.py
pam/activity.py
pam/cli.py
pam/core.py
pam/location.py
pam/operations/combine.py
pam/read/matsim.py
pam/utils.py
pam/write/matsim.py
tests/test_02_activity.py
tests/test_03_read_matsim.py
tests/test_08_write.py
tests/test_17_vehicles.py
tests/test_data/test_matsim_experienced_plans_v12.xml
tests/test_data/test_matsim_plansv12.xml

Changes intended to ensure no data is lost from MATSim plans when read/writing. This mainly includes the unchosen plans, but also other attributes such as link ids and pt interactions with durations (as recently spotted and fixed for elara).
Loosing the unselected plans from bitsim was increasing runs times by 30% (after a pam read/write). I am fairly sure this is caused by matsim loosing the info gained from the top N plans in agent memory.
The cli exposes a flag called `--keep_non_selected/selected_only` which defaults to `keep`. I've made this optional because there will be pretty chonky memory implications.
There's bits and other bobs (this was a long lived branch) - but nothing major and no breaks.

ensures matsim read write maintains data

---

.gitignore
scripts/code-qa/notebook_smoke_tests.py

As per [LAB-1905](https://arupdigital.atlassian.net/browse/LAB-1905); the smoke test is more than 3 times faster now when running locally. The speed improvement when running inside the CI build is smaller (more like 2 X), probably because there are fewer CPU cores available inside the container running the GitHub Action.
Running the smoke test locally took around 150 seconds
Running the smoke test locally takes around 45 seconds
Just to make sure that failed processes are still detected, and that the parent process still produces the correct shell return code when one or more notebooks fail, I deliberately broke one of the notebooks. The failure is still detected, and the process return code is non-zero as it should be (which would break the CI build, as desired).

Make the notebooks smoke test faster

---

README.md

I have recently installed PAM on the EC2 instance I'm using for testing our various code bases against Python 3.11. This experience showed me that there is a minor but crucial gap in the installation instructions around the underlying native geospatial libs (GDAL, PROJ, etc.). I have addressed this for MacOS and Linux (no idea about Windows).
You can see the rendered README [here](https://github.com/arup-group/pam/tree/improve-installation-instructions#readme). I have updated the [table of contents ](https://github.com/arup-group/pam/tree/improve-installation-instructions#contents)and added hyperlinks, and added [a section on installing the native dependencies](https://github.com/arup-group/pam/tree/improve-installation-instructions#underlying-native-dependencies).

Add detail on installing native geospatial libs

---

Dockerfile

This PR fixes the following problem:
Using the docker image built from current Dockerimage gives:
when importing `read_matsim` from `pam.read`

Tkinter install in docker

---

README.md
pam/activity.py
pam/cli.py
pam/core.py
pam/write/matsim.py
tests/test_08_write.py
tests/test_99_cli.py

I've wrapped the recent stream writer in a "context manager" so that it handles the boring xml shenanigans and allows the following low memory functionality:
```
with pam.write.matsim.Writer(path_population_output) as outfile:
for person in pam.read.matsim.stream_matsim_persons(path_population_input, attributes=attributes ):
some_modification(person)
outfile.add_person(person)
```
Hopefully this allows low memory read writing for the cli. However please note that we still require the population attributes to be loaded fully into memory as we are still supporting v11 and, more importantly, experienced plans, which have their attributes in a separate file.
Note that streaming is at the person not household level. I am nervous to extend to a household streamer because i am not sure if we can …

read - write person streaming

---

requirements.txt

sorry.. changing `op` to `predicate` requires at least geopandas 0.10
see https://geopandas.org/en/stable/docs/changelog.html

fix dependency error

---

Dockerfile
run-tests.sh

As it stands, PAM's Dockerfile is broken, which causes our CodeBuild CD pipeline to fail. 
The same error we see in the CD pipeline can be replicated when trying to build the image on my local machine.
```bash
(pam-venv-3.10.10) √ pam % docker build -t pam .
[+] Building 1.8s (7/9)
=> [internal] load build definition from Dockerfile                                                                                                                  0.0s
=> => transferring dockerfile: 413B                                                                                                                                  0.0s
=> [internal] load .dockerignore                                                                                                                                     0.0s
=> => …
```

Replace base docker image

---

pam/__init__.py
pyproject.toml
tests/conftest.py
tests/test_26_optimise_grid.py
tests/test_27_optimise_random.py

I realised the config wasn't capturing coverage correctly (and, quite possibly, the old config didn't either). 
In updating the config to *only* focus on the source code + a plugin I wrote for the docs, coverage dropped to 88.something%, under the 89% threshold. I've now added some basic tests for some parts of the `pam/optimise` scripts, since these had _no_ tests so far. This brings it back over the threshold, but we should probably have a target of no single file below 89% coverage, which the repo wouldn't pass right now.

Fix coverage reporting

---

.github/workflows/build_pipeline.yml
environment.yml
examples/04_Example_Ingest_NTS_Diaries.ipynb
pam/planner/clustering.py
pam/read/matsim.py
pyproject.toml
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
setup.py
tests/test_08_write.py
tests/test_15_cropping.py

PAM should now work on any version from python 3.9 to 3.11, with the CI updated to test the extremes of this range.
It would also be possible to test with some dependencies set to lower bounds to ensure that breaking changes don't creep in (e.g., I've tested locally with pandas=1.5, plotly=4, gdal=3.5 and everything passes, just with some deprecation warnings).
I've put explicit warning ignores for persistent deprecation warnings that are the fault of dependencies, not us.

Update dependencies to work from py3.9 to py3.11

---

pam/utils.py
tests/test_00_utils.py
tests/test_03_read.py

I noticed that your recently merged PR (#216) had tests that had too many assertions in one test. 
On checking that an error is caught, if you have several assertions inside the `with` statement, it will pass provided the first line raises the expected error.
I parametrized a bunch of tests in `test_00_utils.py` which I hope will show how easy it is to do so by default. 
I also added some tests to increase coverage and simplified some util functions that could rely on other functions in the same module, rather than have their own code.
Any checks which are not relevant to the PR can be pre-checked by the PR creator. 
All others should be checked by the reviewer(s). 

Update utils and associated tests

---

.github/workflows/build_pipeline.yml
.github/workflows/daily-scheduled-ci.yml
CHANGELOG.md
README.md
pam/activity.py
pam/read/matsim.py
pam/write/matsim.py
tests/test_02_activity_trips.py

Fixes #221.
Provides "pt" simplification based on removing "pt interaction" activities. Added coverage but am also going to test simplified plans in matsim. Will update.

fix for #221

---

Dockerfile
README.md
docs/contributing/coding.md
docs/installation.md

Fixes #228
Fixes #229
This cleans up some parts of the documentation surrounding installation. E.g., now the short-form install instructions are:
I've also slipped in updating the dockerfile, so that the entry point to the image is plain bash, instead of `python`.
Any checks which are not relevant to the PR can be pre-checked by the PR creator. 
All others should be checked by the reviewer(s). 

Update install instructions and docker entry point

---

.pre-commit-config.yaml

Weekly PRs to update patch versions of `black` and `ruff` seem unnecessary. 
Any checks which are not relevant to the PR can be pre-checked by the PR creator. 
All others should be checked by the reviewer(s). 

Set pre-commit update schedule to monthly

---

CHANGELOG.md
pam/activity.py
tests/test_02_activity_fix.py

Fixes #241.
bug fix - incorrect break statement for cropping plans.
Any checks which are not relevant to the PR can be pre-checked by the PR creator. 
All others should be checked by the reviewer(s). 

fix for issue #241

---

tests/test_100_memory_profiling.py

We're seeing odd behaviour with the timing benchmark in the memory profiling. I had already moved it from 280 seconds to 400 seconds to handle the GitHub Action runners seemingly being slower than local machines. However, in e.g. #249, this 400 second limit was breached (even though locally it still runs in under 280 secs).
The memory profiling is mainly meant to check that memory limits aren't breached, so I think it's OK to remove the timing benchmark. We can always see how long the CI test take in total to get an order-of-magnitude understanding of whether some central component in PAM now leads to long runtimes.
You can add extra checklist items here if …

Remove timing benchmark

---

CHANGELOG.md
pam/read/__init__.py
pam/read/diary.py
tests/test_100_memory_profiling.py

Fixes long memory profiling CI runtimes.
It seems that the timeout that I "fixed" by removing in #254 was actually trying to tell us something. A change in how pandas groupby works means that the current implementation on reading data became _unbelievably_ slow. To be honest, I'm surprised that pivoting a dataframe into a nested dict was applied for "performance" reasons to begin with... 
Anyway, I've got rid of the df->dict conversion. Locally, this not only makes it possible to run the timing/memory benchmark (CI was taking __hours__ for that test!) but actually halves the time it takes to run! Will be interesting to see if this leads to real speed-ups in PAM in more practical applications.
EDIT: this update leads to slower runtimes than the previous method after @Theodore-Chatziioannou …

Fix long run time and reintroduce timing benchmark test

---

.github/workflows/pre-release.yml
.github/workflows/release.yml
CHANGELOG.md
README.md
docs/installation.md
pam/__init__.py
requirements/base.txt

Post-release updates & fixes

---

.github/workflows/daily-scheduled-ci.yml
.github/workflows/docs.yml

- Fixes #277 
The misconfigured channel name my not be the only problem, but it needs fixing in any case and we'll see if the notifications start arriving after that.

Fix the Slack notification channel name in build workflows

---

.github/workflows/daily-scheduled-ci.yml

- Fixes #277 (reopened)
It turns out that Slack notifications from the daily CI build had *two* problems:
- Incorrect target Slack channel name (fixed in [the previous PR](https://github.com/arup-group/pam/pull/278 ))
- Incorrect syntax for passing the build result into the Slack notification action (fixed in this PR)
The literal value `needs.test.result` was being passed to the Slack notification Action, rather than the dynamic value of the build/test Actions job result as intended. The Slack action only sends notifications for the `result` values `success` and `failure`, hence no notification was triggered:
For full in situ verification, we will need to wait until the scheduled daily CI build next runs for PAM after this PR is merged. However, I have used the [same …

Fix syntax for passing CI build result into the Slack notification action

---

.cruft.json
CHANGELOG.md
requirements/dev.txt
src/pam/cli.py
src/pam/operations/snap.py
tests/test_29_snap.py
tests/test_data/test_link_geometry.geojson

Adds CLI method for snapping activity facilities to a network geometry. 
It can be invoked as: `pam snap-facilities <path_population_in> <path_population_out> <path_network_geometry> -f <link_id_field>`
```
pam snap-facilities --help
Usage: pam snap-facilities [OPTIONS] PATH_POPULATION_IN PATH_POPULATION_OUT
PATH_NETWORK_GEOMETRY
Snap facilities to a network geometry.
Options:
-f, --link_id_field TEXT  The link ID field to use in the network shapefile.
Defaults to 'id'.
--help                    Show this message and exit.
```
For each activity, the method will identify the closest link in the shapefile, and add it as a `link=..` attribute to the activity element. Finally, the updated plans file will be saved to a new xml file.
Any checks which are not relevant to the PR can be …

facility link snapping

---

.cruft.json
.editorconfig
.github/pull_request_template.md
.github/workflows/commit-ci.yml
.github/workflows/daily-scheduled-ci.yml
.github/workflows/docs.yml
.github/workflows/pr-ci.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
CONTRIBUTING.md
linkcheck.json

- Fixes #291
I've not updated the changelog because this is not a user-facing change.
I used `cruft update` to bring the CI workflows into line with the cookie-cutter template; that was enough to fix at the broken workflows.
```shell
grep -iRn "mamba" .
./daily-scheduled-ci.yml:22:      cache_mamba_env: false
./daily-scheduled-ci.yml:25:      mamba_env_name: ${{ needs.get-date.outputs.DATE }}
```

Fix the daily CI build

---

.github/workflows/commit-ci.yml
.github/workflows/daily-scheduled-ci.yml
.github/workflows/docs.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

- Fixes #291 
So, the PR I merged to fix the builds used the wrong git tag for some of the actions (`v1.1.1` doesn't exist; we need `v1.1.0` - see [here](https://github.com/arup-group/actions-city-modelling-lab/tags)). Unfortunately, one of the places where the tag was correct was (part of) the CI commit workflow, so the build was fixed for that workflow but broken for the Daily CI, so we only discovered it was broken after merging:

Correct the reusable actions version tags in the CI workflows
